apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp-dev
  namespace: flux-system
spec:
  interval: 30s
  path: ./overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: myteam
  targetNamespace: myapp-dev
