apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp-prod
  namespace: flux-system
spec:
  interval: 30s
  path: ./overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: myteam
  targetNamespace: myapp-prod
